#
# This site was originally deployed by Netlify to https://raj.christmind.info. This has changed
# so that it is incorporated into the Netlify site cmi-www and is accessed at
# https://www.christmind.info/t/raj.
#
# This config file is used update the cmi-raj Netlify site with a page that imforms the user
# that the site has moved and to include a _redirects file that will forward references to 
# https://raj.christmind.info to the appropriate destination.
#
# To develop this site
#
# 1. npm run deploy:netlify
# 2. Edit moved.md, _redirects and any other files
# 3. Test locally at localhost:9912
# 4. Use the command line from the project root to deploy to Netlify
#     $ netlify deploy --prod
#
# The switch from https://raj.christmind.info to https://www.christmind.info/t/acol happened
# on March 19, 2019. Maintaining the old Netlify site, cmi-raj, is needed only for a short 
# time.
#
#
# CMI
sourceId: 13
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'The Raj Material'
tagline:      ''
description:  ''
url:          'https://raj.christmind.info'
baseurl:      ''
keywords:     "Christ Mind, Jesus, Paul Tuttle, Raj, NWFFACIM, ACIM, ACIM Sparkly Edition"
src-url:      'https://raj.christmind.info'
port:         9913

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

include: [ _redirects ]

exclude: [
  deploy,
  LICENSE,
  README.md,
  Gemfile,
  Gemfile.lock,
  package.json,
  package-lock.json,
  node_modules,
  webpack.config.js,
  src,
  project,
  _yaa,
  _grad,
  _sg2002,
  _sg2003,
  _sg2004,
  _sg2005,
  _sg2006,
  _sg2007,
  _sg2008,
  _sg2009,
  _sg2010,
  _sg2011,
  _sg2012,
  _sg2013,
  _sg2014,
  _sg2015,
  _sg2016,
  _sg2017,
  _sg2018
]

